# Vectorization in Array

In [1]:
import numpy as np

In [2]:
list_1 = [1,2,3,4,5,66,7,7,777,9]

In [3]:
list_1 = np.array(list_1)

In [4]:
list_2 = np.arange(10)*12

In [5]:
list_2

array([  0,  12,  24,  36,  48,  60,  72,  84,  96, 108])

In [6]:
list_1 + list_2

array([  1,  14,  27,  40,  53, 126,  79,  91, 873, 117])

In [9]:
list_random_num = np.random.randn(2,4)

In [11]:
list_random_num

array([[-1.16314243, -0.43169322, -1.87581239,  1.06625983],
       [-0.80245258,  0.10177382,  0.06468989, -0.55719627]])